# Generated by Django 5.2 on 2025-04-28 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='Not Specified', max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
