# Generated by Django 5.2 on 2025-04-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_authors_delete_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
