# Generated by Django 5.2 on 2025-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
