# Generated by Django 5.2 on 2025-05-02 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_subtitle_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
